# -*- coding: utf-8 -*-
"""studentmanagementsystem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15fM10AmQHCTLyAnreb2Jxu6nCvZX1den
"""

# Student Management System

print("************* STUDENT MANAGEMENT SYSTEM *************")

students = [
    {'name': 'Abhinav', 'id': 1, 'age': 21, 'course': 'science', 'marks': [12, 25, 13]},
    {'name': 'Abhi', 'id': 2, 'age': 21, 'course': 'science', 'marks': [13, 26, 23]}
]


while True:

    print("\n1. ADD")
    print("2. VIEW")
    print("3. DELETE")
    print("4. UPDATE")
    print("5. SEARCH")
    print("6. EXIT")

    choice = input("Enter your choice: ")

    match choice:

        case "1":
            print("\n--- ADD STUDENT ---")

            name = input("Enter name of the student: ")
            id = int(input("Enter ID of the student: "))
            age = int(input("Enter age of the student: "))
            course = input("Enter course of the student: ")

            marks = []
            marks.append(int(input("Enter mark 1: ")))
            marks.append(int(input("Enter mark 2: ")))
            marks.append(int(input("Enter mark 3: ")))

            student = {
                'name': name,
                'id': id,
                'age': age,
                'course': course,
                'marks': marks
            }

            students.append(student)

            print("Student added successfully!")


        case "2":
            print("\n--- STUDENT RECORDS ---")

            if len(students) == 0:
                print("No students found.")

            else:
                for student in students:
                    print("\nID     :", student['id'])
                    print("Name   :", student['name'])
                    print("Age    :", student['age'])
                    print("Course :", student['course'])
                    print("Marks  :", student['marks'])


        case "3":
            print("\n--- DELETE STUDENT ---")

            delete_id = int(input("Enter student ID to delete: "))

            found = False

            for student in students:
                if student['id'] == delete_id:
                    students.remove(student)
                    print("Student deleted successfully!")
                    found = True
                    break

            if found == False:
                print("Student not found.")


        case "4":
            print("\n--- UPDATE STUDENT ---")

            update_id = int(input("Enter student ID to update: "))

            found = False

            for student in students:

                if student['id'] == update_id:

                    print("Student found!")

                    student['name'] = input("Enter new name: ")
                    student['age'] = int(input("Enter new age: "))
                    student['course'] = input("Enter new course: ")

                    student['marks'][0] = int(input("Enter new mark 1: "))
                    student['marks'][1] = int(input("Enter new mark 2: "))
                    student['marks'][2] = int(input("Enter new mark 3: "))

                    print("Student updated successfully!")

                    found = True
                    break

            if found == False:
                print("Student not found.")


        case "5":
            print("\n--- SEARCH STUDENT ---")

            search = input("Enter student ID or name: ")

            found = False

            for student in students:

                if str(student['id']) == search or student['name'].lower() == search.lower():

                    print("\nStudent Found!")
                    print("ID     :", student['id'])
                    print("Name   :", student['name'])
                    print("Age    :", student['age'])
                    print("Course :", student['course'])
                    print("Marks  :", student['marks'])

                    found = True
                    break

            if found == False:
                print("Student not found.")


        case "6":
            print("\nThank you for using Student Management System!")
            break

        case _:
            print("Invalid choice! Please enter 1-6.")